<?php
/**
 * @package Divante\GoogleTagManager
 * @author Adam Sprada <adam@sprada.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license See LICENSE for license details.
 */
?>

<?php /** @var $block \Divante\GoogleTagManager\Block\Gtm **/ ?>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push(
{'gtm.start': new Date().getTime(),event:'gtm.js'}
);var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<?php echo $block->getAccountId(); ?>');</script>
<!-- End Google Tag Manager -->
