<?php
/**
 * @package Divante\GoogleTagManager
 * @author Adam Sprada <adam@sprada.pl>
 * @copyright 2017 Divante Sp. z o.o.
 * @license See LICENSE for license details.
 */
?>

<?php /** @var $block \Divante\GoogleTagManager\Block\Gtm **/ ?>

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $block->getAccountId(); ?>"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
